#!/usr/bin/env python
"""Plan the same ligand series 21 ways and build a side-by-side report.

Every other example asks what one network looks like. This one asks what the *knobs*
cost: it runs ``rbfenet plan`` 21 times over one 16-ligand series, changing only the
flags, collects metrics that are comparable across all of them, and renders a single
index page linking each variant to its own report.

The published output of this script is the Tyk2 variant matrix in the documentation,
regenerated by::

    python examples/06_variant_matrix.py docs/source/_static/tyk2-matrix

It takes roughly 45 s and writes about 67 MB, nearly all of it self-contained HTML.
Pass ``--ligands`` to run the same comparison over a series of your own; the numbers in
the prose below are Tyk2's and are only claimed for the shipped set.
"""

from __future__ import annotations

import argparse
import html
import json
import math
import subprocess
import sys
import time
from pathlib import Path

import networkx as nx

DATA = Path(__file__).resolve().parent / "data" / "tyk2"

# The same 21 variants planned before the stranded-core repair landed (#39/#42). Frozen: it
# cannot be regenerated from a current checkout, which is exactly why it is kept. Delete it
# and the "what the repair changed" section simply drops out of the page.
PRE_REPAIR = DATA / "matrix-pre-repair.json"

SEED = "20260824"

# (key, section, label, extra plan flags, extra exporters)
VARIANTS = [
    ("mst-default", "Topology", "mst, edges-per-ligand 2 (default)", [], ["amber"]),
    ("mst-epl3", "Topology", "mst, edges-per-ligand 3", ["--edges-per-ligand", "3"], []),
    ("mst-epl4", "Topology", "mst, edges-per-ligand 4", ["--edges-per-ligand", "4"], []),
    ("rmst-n2", "Topology", "redundant-mst, n-redundancy 2", ["--planner", "redundant-mst", "--n-redundancy", "2"], []),
    ("rmst-n3", "Topology", "redundant-mst, n-redundancy 3", ["--planner", "redundant-mst", "--n-redundancy", "3"], []),
    ("star-most-partners", "Topology", "star, hub by most_partners", ["--planner", "star"], []),
    (
        "star-min-total-cost",
        "Topology",
        "star, hub by min_total_cost",
        ["--planner", "star", "--hub-selection", "min_total_cost"],
        [],
    ),
    ("complete", "Topology", "complete (upper reference, not a proposal)", ["--planner", "complete"], []),
    ("diameter-4", "Path length and cycles", "mst, max-diameter 4", ["--max-diameter", "4"], []),
    ("diameter-3", "Path length and cycles", "mst, max-diameter 3", ["--max-diameter", "3"], []),
    (
        "cycle-coverage-edge",
        "Path length and cycles",
        "mst, cycle-coverage-mode edge (FEP+ invariant)",
        ["--cycle-coverage-mode", "edge"],
        [],
    ),
    (
        "a-optimal-44",
        "Statistical design",
        "variance scorer, A-optimal, 44 edges",
        ["--scorer", "variance", "--planner", "optimal", "--design", "a_optimal", "--n-edges", "44"],
        [],
    ),
    (
        "d-optimal-44",
        "Statistical design",
        "variance scorer, D-optimal, 44 edges",
        ["--scorer", "variance", "--planner", "optimal", "--design", "d_optimal", "--n-edges", "44"],
        [],
    ),
    (
        "a-optimal-44-allocated",
        "Statistical design",
        "A-optimal, 44 edges, 400 ns budget allocated",
        [
            "--scorer",
            "variance",
            "--planner",
            "optimal",
            "--design",
            "a_optimal",
            "--n-edges",
            "44",
            "--design-total-ns",
            "400",
        ],
        ["amber"],
    ),
    ("cbfe-all", "Counterpoised", "--cbfe all (whole network counterpoised)", ["--cbfe", "all"], ["amber"]),
    (
        "cbfe-cycles",
        "Counterpoised",
        "--cbfe cycles (counterpoised only where they buy cycle coverage)",
        ["--cbfe", "cycles"],
        [],
    ),
    (
        "cbfe-cycles-edgecov",
        "Counterpoised",
        "--cbfe cycles + --cycle-coverage-mode edge (the combination that spends the CBFE pool)",
        ["--cbfe", "cycles", "--cycle-coverage-mode", "edge"],
        [],
    ),
    ("cbfe-bridge", "Counterpoised", "--cbfe bridge", ["--cbfe", "bridge"], []),
    ("consistency-component", "Soft-core consistency", "--consistency component", ["--consistency", "component"], []),
    (
        "consistency-graph",
        "Soft-core consistency",
        "--consistency graph (one scmask per ligand)",
        ["--consistency", "graph"],
        ["amber"],
    ),
    ("compat-v0.4", "Reference", "--compat v0.4 (released behaviour)", ["--compat", "v0.4"], []),
]

# What each variant is asking, in plain terms. Keyed by the variant key.
WHY = {
    "mst-default": "The shipped default. Minimum spanning tree, then edges added until every ligand has 2. Everything else is compared to this.",
    "mst-epl3": "Raise the per-ligand degree target to 3. More edges, more redundancy, more GPU time.",
    "mst-epl4": "Degree target 4. Approaching the n&middot;ln(n) floor by brute force.",
    "rmst-n2": "Overlay 2 spanning trees before adding degree redundancy. A different route to redundancy than raising degree.",
    "rmst-n3": "Overlay 3 spanning trees. Lands almost exactly on the 45-edge floor.",
    "star-most-partners": "Every ligand connected to one hub, chosen as the ligand with the most feasible partners.",
    "star-min-total-cost": "Same star, but the hub is the ligand whose edges are cheapest in total.",
    "complete": "Every feasible pair. Not a proposal &mdash; the upper bound that makes the others readable.",
    "diameter-4": "Keep adding edges until no two ligands are more than 4 perturbations apart.",
    "diameter-3": "Same, tightened to 3. Shorter chains, more edges.",
    "cycle-coverage-edge": "Demand that every <em>edge</em> lie on a cycle, not merely every ligand. The FEP+ invariant.",
    "a-optimal-44": "Pick 44 edges minimising the average variance of the predicted affinities (trace of the covariance).",
    "d-optimal-44": "Pick 44 edges minimising the covariance determinant. Tends to produce more cycles than A-optimal.",
    "a-optimal-44-allocated": "The A-optimal network, plus a 400 ns simulation budget divided across its edges by predicted information gain.",
    "cbfe-all": "Replace every edge with a counterpoised (CBFE) calculation. No atom mapping needed at all.",
    "cbfe-cycles": "Allow counterpoised edges, but only where they would buy cycle coverage.",
    "cbfe-cycles-edgecov": "The combination that actually forces the question: CBFE allowed <em>and</em> every edge required on a cycle.",
    "cbfe-bridge": "Allow counterpoised edges only to join otherwise-disconnected pieces.",
    "consistency-component": "Force one soft-core per ligand within each connected component, so a ligand keeps one scmask.",
    "consistency-graph": "Force one soft-core per ligand across the whole network.",
    "compat-v0.4": "Reproduce released v0.4 behaviour exactly. Confirms none of the above drifted the baseline.",
}


# ---------------------------------------------------------------------------
# Planning
# ---------------------------------------------------------------------------


def graph_metrics(net_path: Path) -> dict:
    """Return bridge count, cycle coverage and soft-core uniformity for a network.

    Parameters
    ----------
    net_path
        Path to a network JSON file written by ``rbfenet plan``.

    Returns
    -------
    dict
        Metrics ``diagnose`` does not itself report. ``n_nonuniform_softcore`` counts
        ligands carrying more than one distinct soft-core mask across their edges --
        each of those needs a different Amber ``scmask`` per edge.
    """
    net = json.loads(net_path.read_text())
    graph = nx.Graph()
    graph.add_nodes_from(lig["name"] for lig in net["ligands"])
    kinds = {}
    softcore: dict[str, set] = {}
    for edge in net["edges"]:
        a, b = edge["source"], edge["target"]
        graph.add_edge(a, b)
        kinds[(a, b)] = edge.get("kind", "rbfe")
        mapping = edge.get("mapping") or {}
        for ligand, field in ((a, "sc1"), (b, "sc2")):
            if field in mapping:
                softcore.setdefault(ligand, set()).add(tuple(sorted(mapping[field])))

    nonuniform = sorted(name for name, masks in softcore.items() if len(masks) > 1)
    n_rejected = sum(1 for c in net.get("candidates", []) if (c.get("score") or {}).get("rejections"))
    bridges = list(nx.bridges(graph)) if graph.number_of_edges() else []
    on_cycle = {n for n in graph.nodes if any(n in c for c in nx.cycle_basis(graph))}
    edge_on_cycle = sum(1 for a, b in graph.edges if (a, b) not in bridges and (b, a) not in bridges)
    return {
        "n_bridges": len(bridges),
        "node_cycle_coverage": len(on_cycle) / graph.number_of_nodes() if graph.number_of_nodes() else 0.0,
        "edge_cycle_coverage": edge_on_cycle / graph.number_of_edges() if graph.number_of_edges() else 0.0,
        "n_components": nx.number_connected_components(graph),
        "hub": max(dict(graph.degree).items(), key=lambda kv: kv[1])[0] if graph.number_of_edges() else None,
        "n_cbfe_edges": sum(1 for k in kinds.values() if k != "rbfe"),
        "n_rejected": n_rejected,
        "n_nonuniform_softcore": len(nonuniform),
        "nonuniform_softcore": nonuniform,
    }


def run_matrix(ligands: list[Path], out: Path, jobs: int) -> list[dict]:
    """Plan every variant and return one metrics record per variant.

    A variant that fails to plan is recorded with an ``error`` key rather than aborting
    the run: one bad flag combination should not cost the other twenty.
    """
    cli = [sys.executable, "-m", "rbfenetmap.cli.main"]
    results = []
    for key, section, label, flags, extra_exports in VARIANTS:
        vdir = out / key
        vdir.mkdir(parents=True, exist_ok=True)
        net = vdir / "network.json"
        exporters = ["html", "json", "edgelist", "graphml", *extra_exports]
        cmd = [
            *cli,
            "plan",
            "--ligands",
            *[str(p) for p in ligands],
            "--jobs",
            str(jobs),
            "--out",
            str(net),
            "--export",
            *exporters,
            "--export-dir",
            str(vdir),
            *flags,
        ]
        started = time.time()
        proc = subprocess.run(cmd, capture_output=True, text=True)
        elapsed = time.time() - started

        record = {
            "key": key,
            "section": section,
            "label": label,
            "flags": " ".join(flags) or "(defaults)",
            "seconds": round(elapsed, 1),
        }
        if proc.returncode != 0 or not net.exists():
            tail = (proc.stderr or proc.stdout).strip().splitlines()
            record["error"] = tail[-1] if tail else "failed"
            print(f"FAIL {key}: {record['error']}")
            results.append(record)
            continue

        (vdir / "plan.stdout.txt").write_text(proc.stdout)
        diag = subprocess.run(
            [*cli, "diagnose", "--network", str(net), "--seed", SEED, "--format", "json"],
            capture_output=True,
            text=True,
        )
        record.update(json.loads(diag.stdout))
        (vdir / "diagnose.json").write_text(diag.stdout)
        table = subprocess.run(
            [*cli, "diagnose", "--network", str(net), "--seed", SEED, "--format", "table"],
            capture_output=True,
            text=True,
        )
        (vdir / "diagnose.txt").write_text(table.stdout)
        record.update(graph_metrics(net))
        results.append(record)
        print(f"ok   {key}: {record['n_edges']} edges, cost {record['cost']:.2f}, {elapsed:.1f}s")
    return results


# ---------------------------------------------------------------------------
# The index page
# ---------------------------------------------------------------------------

CSS = """
:root{--bg:#fff;--fg:#16181d;--muted:#5b6472;--line:#e3e6eb;--accent:#1b5e9c;
--warn:#8a5a00;--warnbg:#fdf6e3;--good:#1f6b3a;--card:#f7f8fa;}
@media(prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#14161a;--fg:#e8eaed;
--muted:#9aa3b0;--line:#2b2f36;--accent:#6fb3ea;--warn:#e0b050;--warnbg:#2a2415;
--good:#6cc48d;--card:#1c1f25;}}
*{box-sizing:border-box}
body{background:var(--bg);color:var(--fg);margin:0;padding:2.5rem 1.5rem 5rem;
font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;}
.wrap{max-width:1180px;margin:0 auto}
h1{font-size:1.9rem;margin:0 0 .3rem;letter-spacing:-.02em}
h2{font-size:1.25rem;margin:2.8rem 0 .8rem;padding-bottom:.35rem;border-bottom:2px solid var(--line)}
h3{font-size:1rem;margin:1.6rem 0 .5rem}
.sub{color:var(--muted);margin:0 0 1.6rem}
.scroll{overflow-x:auto;-webkit-overflow-scrolling:touch;border:1px solid var(--line);border-radius:8px}
table{border-collapse:collapse;width:100%;font-size:.86rem;min-width:900px}
th,td{padding:.5rem .6rem;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}
th{background:var(--card);font-weight:600;position:sticky;top:0}
td.l,th.l{text-align:left}
tbody tr:hover{background:var(--card)}
.sec td{background:var(--card);font-weight:700;text-align:left;color:var(--accent);
font-size:.78rem;letter-spacing:.06em;text-transform:uppercase}
a{color:var(--accent)}
code{background:var(--card);padding:.1em .35em;border-radius:4px;font-size:.88em}
.note{background:var(--warnbg);border-left:3px solid var(--warn);padding:.9rem 1.1rem;
border-radius:0 6px 6px 0;margin:1.2rem 0}
.note strong{color:var(--warn)}
.below{color:var(--warn);font-weight:600}
.ok{color:var(--good)}
.legend{color:var(--muted);font-size:.85rem;margin-top:.7rem}
.legend dt{font-weight:600;color:var(--fg);float:left;clear:left;margin-right:.5em}
.legend dd{margin:0 0 .2rem}
td.l{white-space:normal;min-width:290px;max-width:340px}
.flags{color:var(--muted);font-size:.82em;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.why{color:var(--muted);font-size:.82em;display:block;margin-top:.25rem;line-height:1.4}
.knobs{margin:1rem 0 0}
.knobs dt{font-weight:600;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.86rem;margin-top:.7rem}
.knobs dd{margin:.1rem 0 0;color:var(--muted);font-size:.9rem}
.tool{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:.9rem 1.1rem;margin:0 0 1.4rem;font-size:.92rem}
.meta{color:var(--muted);font-size:.88rem}
"""


def _softcore_section(rows: list[dict], before: dict[str, dict]) -> str:
    """Render the before/after table for the stranded-core repair fix.

    Returns an empty string when no pre-repair baseline is available, which is what
    makes the baseline file optional rather than required.
    """
    if not before:
        return ""
    moved, same = [], 0
    for row in rows:
        prior = before.get(row["key"])
        if not prior:
            continue
        if prior.get("n_edges") != row.get("n_edges") or abs(prior.get("cost", 0) - row.get("cost", 0)) > 1e-6:
            moved.append((row, prior))
        else:
            same += 1
    body = "".join(
        f"<tr><td class='l'><a href='{r['key']}/network.html'>{html.escape(r['key'])}</a></td>"
        f"<td>{b['n_edges']}</td><td>{b['cost']:.2f}</td>"
        f"<td>{r['n_edges']}</td><td>{r['cost']:.2f}</td>"
        f"<td>{b.get('n_rejected', 0)} &rarr; {r.get('n_rejected', 0)}</td></tr>"
        for r, b in moved
    )
    return f"""<h2>What the soft-core repair fix changed</h2>
<p>Four pairs used to be refused for <code>softcore_multiple_attachments</code>:
<code>ejm42~ejm44</code>, <code>ejm42~ejm55</code>, <code>ejm43~ejm55</code>,
<code>ejm44~ejm55</code>. The MCS kept a terminal methyl in the common core while the atom
joining it to the rest of the core went soft-core, so the soft-core became a bridge rather than
a substituent. The repair now absorbs the stranded fragment, and the pool is
<strong>120 of 120 feasible</strong> with <strong>no rejections anywhere</strong>.</p>
<div class="note">
<strong>It moved less than the headline suggests.</strong> The recovered edges cost
1.544&ndash;2.354 against a selected range of 0.273&ndash;1.983, because the demotion is charged
through the scorer's <code>repair_cost</code> term (0.75 per demoted atom). So the default
network is <em>identical</em>, and {same} of the {len(rows)} variants did not move at all. Only
the denser ones did:
</div>
<div class="scroll"><table><thead><tr>
<th class="l">variant</th><th colspan="2">before the fix</th><th colspan="2">after</th><th>rejected</th>
</tr><tr><th class="l"></th><th>edges</th><th>cost</th><th>edges</th><th>cost</th><th></th></tr></thead>
<tbody>{body}</tbody></table></div>
<p class="meta">The gain is a candidate pool that stops refusing edges it can run, not a cheaper
default network. <code>--edges-per-ligand 4</code> is the clearest win: degree four reached with
one fewer edge, and cheaper.</p>"""


def cell(row: dict, key: str, fmt: str = "{}") -> str:
    """Format one metric, rendering a missing value as an em dash."""
    value = row.get(key)
    return "&mdash;" if value is None else fmt.format(value)


def build_row(row: dict, floor: int) -> str:
    """Render one variant as a table row, linking to its own report."""
    degree = row.get("degree", {})
    n_edges = row.get("n_edges", 0)
    short = floor - n_edges
    floor_cell = f'<span class="below">&minus;{short}</span>' if short > 0 else f'<span class="ok">+{-short}</span>'
    link = f'<a href="{row["key"]}/network.html">{html.escape(row["key"])}</a>'
    cbfe = row.get("n_cbfe_edges", 0)
    return f"""<tr>
<td class="l">{link}<br><span class="flags">{html.escape(row["flags"])}</span>
<br><span class="why">{WHY.get(row["key"], "")}</span></td>
<td>{n_edges}</td><td>{floor_cell}</td>
<td>{cell(row, "cost", "{:.2f}")}</td><td>{cell(row, "gpu_hours", "{:.0f}")}</td>
<td>{degree.get("min", "&mdash;")}/{degree.get("mean", 0):.1f}/{degree.get("max", "&mdash;")}</td>
<td>{cell(row, "diameter")}</td>
<td>{cell(row, "n_cycles")}</td>
<td>{cell(row, "n_bridges")}</td>
<td>{row.get("edge_cycle_coverage", 0) * 100:.0f}%</td>
<td>{row.get("n_nonuniform_softcore", "&mdash;")}</td>
<td>{row.get("n_rejected", "&mdash;") or "&mdash;"}</td>
<td>{cbfe if cbfe else "&mdash;"}</td>
<td>{row.get("robustness", {}).get("connected_fraction", "&mdash;")}</td>
</tr>"""


HEAD = """<tr>
<th class="l">variant</th><th>edges</th><th>vs floor</th><th>cost</th><th>GPU&nbsp;h</th>
<th>deg min/mean/max</th><th>diam</th><th>cycles&nbsp;&le;4</th><th>bridges</th>
<th>edge&nbsp;cyc&nbsp;cov</th><th>non&#8209;uniform&nbsp;SC</th><th>rejected</th><th>CBFE</th><th>robust</th>
</tr>"""


def build_index(rows: list[dict], out: Path, n_ligands: int) -> Path:
    """Write the side-by-side index page over every planned variant.

    The ``n ln n`` floor is taken from ``diagnose``'s own ``edge_budget`` rather than
    recomputed here, so the page always agrees with the tool it is reporting. Note the
    package rounds that floor two ways -- ``diagnostics`` ceils it, ``optimal_planner``
    rounds it -- and for n=16 they disagree by one.
    """
    budgets = [r["edge_budget"]["recommended"] for r in rows if isinstance(r.get("edge_budget"), dict)]
    floor = budgets[0] if budgets else (math.ceil(n_ligands * math.log(n_ligands)) if n_ligands > 1 else 0)
    before = {r["key"]: r for r in json.loads(PRE_REPAIR.read_text())} if PRE_REPAIR.exists() else {}

    seen: list[str] = []
    for row in rows:
        if row["section"] not in seen:
            seen.append(row["section"])
    body = []
    for section in seen:
        body.append(f'<tr class="sec"><td colspan="14">{html.escape(section)}</td></tr>')
        body += [build_row(r, floor) for r in rows if r["section"] == section]

    page = f"""<title>Tyk2 Network Variants</title>
<style>{CSS}</style>
<div class="wrap">
<h1>Tyk2 RBFE network variants</h1>
<p class="sub">{n_ligands} ligands &middot; every pair feasible &middot; one connected component.
Every row is a real planning run; click a variant for its full report.</p>

<div class="tool">
Planned with <strong>rbfe-network-map</strong> (<code>rbfenetmap</code>). Every row is one
<code>rbfenet plan</code> invocation over the same {n_ligands} input structures, shipped in
<code>examples/data/tyk2/</code>; the flags shown are the only difference between them.
Regenerate the whole page with
<code>python examples/06_variant_matrix.py docs/source/_static/tyk2-matrix</code>.
</div>

<div class="note">
<strong>Optimal design buys precision, not accuracy.</strong> The two optimal-design rows below
implement <strong>NetBFE</strong> &mdash; a published method by Li et&nbsp;al., not part of this
package and not a mode of it. In that paper <code>tr(C)</code> fell monotonically
(1.08&nbsp;&rarr;&nbsp;0.78) as the design was optimised while RMSE against experiment
<em>rose</em> (0.84&nbsp;&rarr;&nbsp;0.91), measured on <strong>16 TYK2 inhibitors</strong> &mdash;
almost certainly this same <code>ejm*</code>/<code>jmc*</code> series. Minimising predicted
variance does not make the underlying free energies more correct.
<p style="margin:.7rem 0 0">Note also that the published method is <em>iterative</em>:
it re-optimises allocation each round from variances measured in the previous one. The rows here
are the static first pass, with no MD round trip behind them.</p>
<p style="margin:.7rem 0 0;font-size:.86rem">Li, P.; Li, Z.; Wang, Y.; Dou, H.; Radak, B.&nbsp;K.;
Allen, B.&nbsp;K.; Sherman, W.; Xu, H. &ldquo;Precise Binding Free Energy Calculations for Multiple
Molecules Using an Optimal Measurement Network of Pairwise Differences.&rdquo;
<em>J.&nbsp;Chem.&nbsp;Theory Comput.</em> <strong>2022</strong>, <em>18</em>(2), 650&ndash;663.
<a href="https://doi.org/10.1021/acs.jctc.1c00703">doi:10.1021/acs.jctc.1c00703</a></p>
</div>

<div class="scroll"><table><thead>{HEAD}</thead><tbody>
{"".join(body)}
</tbody></table></div>

<dl class="legend">
<dt>vs floor</dt><dd>edges relative to the <code>n&middot;ln(n)</code> = <strong>{floor}</strong>
precision floor for n={n_ligands} (Pitman 2023). Negative is below it.</dd>
<dt>cost</dt><dd>scorer units. <strong>Comparable only within one scorer.</strong> The
A&#8209;/D&#8209;optimal rows use the <code>variance</code> scorer (kcal/mol predicted &sigma;)
and their cost is <em>not</em> on the same scale as the <code>linear</code>-scorer rows.
GPU&nbsp;h is comparable across every row.</dd>
<dt>non-uniform SC</dt><dd>ligands carrying more than one distinct soft-core mask across their
edges &mdash; each one needs a different <code>scmask</code> per edge in Amber.</dd>
<dt>rejected</dt><dd>candidate pairs the feasibility gate refused. Each one is drawn in the
variant's own report, under &ldquo;Rejected candidates&rdquo;, with the mapping that provoked it.</dd>
<dt>robust</dt><dd>fraction of 100 Monte-Carlo trials still connected at a 5% per-edge failure
rate (seed {SEED}).</dd>
</dl>

{_softcore_section(rows, before)}

<h2>What each option does</h2>
<dl class="knobs">
<dt>--edges-per-ligand N</dt><dd>Target minimum degree. After the spanning tree is fixed, edges are
added until every ligand has at least N. The main redundancy dial (default 2).</dd>
<dt>--planner redundant-mst --n-redundancy N</dt><dd>Overlay N spanning trees, then apply the usual
degree and cycle redundancy on top. Redundancy from independent trees rather than from degree.</dd>
<dt>--planner star [--hub-selection ...]</dt><dd>Connect every ligand to one hub.
<code>most_partners</code> picks the ligand with the most feasible edges; <code>min_total_cost</code>
the one whose edges are cheapest in total.</dd>
<dt>--planner complete</dt><dd>Select every feasible candidate pair. A reference point.</dd>
<dt>--max-diameter N</dt><dd>Add edges until no two ligands are more than N perturbations apart.
Long chains are where error accumulates; LOMAP caps at 6, FEP+ works below 5.</dd>
<dt>--cycle-coverage-mode {{node,edge}}</dt><dd><code>node</code> (default) asks that every
<em>ligand</em> lie on a cycle. <code>edge</code> asks that every <em>edge</em> does &mdash; strictly
stronger, and what makes cycle-closure error checking apply to every transformation.</dd>
<dt>--scorer variance</dt><dd>Score edges as a predicted standard deviation in kcal/mol rather than
on an arbitrary difficulty scale. Required for optimal design, which needs a real &sigma;.</dd>
<dt>--planner optimal --design {{a_optimal,d_optimal}}</dt><dd>Choose edges to minimise a functional of
the estimate covariance <code>C</code>. <strong>A-optimal</strong> minimises <code>tr(C)</code>, the
average variance. <strong>D-optimal</strong> minimises <code>det(C)</code>, which favours more cycles.</dd>
<dt>--design-total-ns NS</dt><dd>Divide a total simulation budget across the selected edges by
predicted information gain, and write per-edge &lambda; windows and nanoseconds into the Amber
runconfigs.</dd>
<dt>--cbfe {{off,bridge,cycles,all}}</dt><dd>Allow counterpoised edges &mdash; two absolute calculations
run in opposite directions, needing no atom mapping. <code>bridge</code> only to join disconnected
pieces, <code>cycles</code> also to close cycles, <code>all</code> for the entire network.</dd>
<dt>--consistency {{pairwise,component,graph}}</dt><dd>How widely a ligand's soft-core must agree.
<code>pairwise</code> (default) lets each edge choose its own; <code>component</code> forces one per
ligand within a component; <code>graph</code> forces one across the whole network &mdash; which is
what lets a ligand keep a single Amber <code>scmask</code>.</dd>
<dt>--compat v0.4</dt><dd>Pin every algorithmic knob to released v0.4 behaviour, so a known result
stays reachable by name.</dd>
</dl>

<h2>What the runs actually showed</h2>

<h3>Nothing is rejected any more</h3>
<p>Every pair in the set is now feasible: <strong>120 of 120</strong>. Until the stranded-core
repair landed, four pairs &mdash; <code>ejm42~ejm44</code>, <code>ejm42~ejm55</code>,
<code>ejm43~ejm55</code> and <code>ejm44~ejm55</code> &mdash; were refused for
<code>softcore_multiple_attachments</code>. The MCS had kept a terminal methyl in the common core
while the atom joining it to the rest of the core went soft-core, which made the soft-core a
bridge rather than a substituent. The repair now absorbs the stranded fragment instead of
rejecting the edge.</p>
<p>It changed less than you might expect. The recovered edges cost 1.544&ndash;2.354 against a
selected range of 0.273&ndash;1.983, because the demotion is charged through the scorer's
<code>repair_cost</code> term, so <strong>the default network is identical</strong>. Only the
denser variants move: <code>--edges-per-ligand 4</code> now reaches degree four with 32 edges
instead of 33 and costs less, <code>complete</code> gains the four edges, and the two optimal
designs swap a few for marginally better totals.</p>

<h3>The default network is below the floor and has three bridges</h3>
<p><code>mst</code> at the default <code>--edges-per-ligand 2</code> gives 20 edges &mdash; 25
short of the 45-edge floor &mdash; a diameter of 7, and three bridge edges. Node cycle coverage
is already 1.0, which is why the default stops there, but 15% of edges sit on no cycle at all
and cannot be error-checked. Its robustness is the worst of any connected variant: only
<strong>77%</strong> of failure trials stay connected.</p>

<h3><code>--cycle-coverage-mode edge</code> is nearly free</h3>
<p>It swaps exactly one edge (still 20 total), and takes bridges 3&nbsp;&rarr;&nbsp;0 and edge
cycle coverage 85%&nbsp;&rarr;&nbsp;100% for +1.79 cost and no extra GPU time. On this set it
is the single best value change to the default.</p>

<h3>Both star hub heuristics pick the same ligand, by coincidence</h3>
<p><code>ejm46</code> is simultaneously tied for most partners (15) and the strict
minimum-total-cost hub (22.70, next best 23.55). So <code>--hub-selection min_total_cost</code>
is genuinely evaluated here but changes nothing &mdash; this set does not discriminate the two
heuristics. Either way the star has 15 bridges and zero cycles: no cycle closure anywhere, so
no internal consistency check.</p>

<h3>CBFE edges are never competitive on this set</h3>
<p><code>--cbfe bridge</code> and <code>--cbfe cycles</code> both return the default network
unchanged. That is not an inert flag: <code>cycles</code> mode does stock the CBFE pool, but
with node coverage already satisfied nothing spends it. Forcing the issue with
<code>--cbfe cycles --cycle-coverage-mode edge</code> still selects <strong>zero</strong> CBFE
edges &mdash; the result is identical to the pure-RBFE <code>cycle-coverage-edge</code> run.
With every pair feasible there is always a cheaper RBFE edge available. CBFE is
worth reaching for on this series only as a deliberate methodological choice, not for topology.</p>

<h3><code>--cbfe all</code> costs 3.2&times; per edge</h3>
<p>23 counterpoised edges at <strong>12.70</strong> GPU&nbsp;h each against
<strong>3.97</strong> for the 20 RBFE edges &mdash; a per-edge ratio of
<strong>3.20&times;</strong>. Whole-network: 79&nbsp;&rarr;
292 GPU&nbsp;h, a 3.68&times; increase. It also plans in 0.5&nbsp;s because it needs no mapping.</p>

<h3>Soft-core consistency is the one that changes the Amber setup</h3>
<p>Under every default-mapping variant, <strong>8 of 16</strong> ligands carry more than one
distinct soft-core mask across their edges &mdash; a different <code>scmask</code> per edge for
half the series. Both <code>--consistency component</code> and <code>--consistency graph</code>
take that to <strong>0</strong>, on the identical 20-edge topology, for +4.75 cost
(20.00&nbsp;&rarr;&nbsp;24.75) and no change in GPU hours. The two modes give byte-identical
networks here because the candidate pool is a single component.</p>
</div>
"""
    path = out / "index.html"
    path.write_text(page)
    return path


# ---------------------------------------------------------------------------


def main() -> int:
    """Plan every variant, then render the index over them."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("out", type=Path, help="Directory to write the variant reports into.")
    parser.add_argument(
        "--ligands",
        type=Path,
        nargs="+",
        default=None,
        help=f"Ligand files or a directory. Defaults to the shipped Tyk2 series in {DATA}.",
    )
    parser.add_argument("--jobs", type=int, default=8, help="Worker processes per plan (default: 8).")
    parser.add_argument(
        "--index-only", action="store_true", help="Skip planning and rebuild index.html from an existing matrix.json."
    )
    args = parser.parse_args()

    paths = args.ligands or [DATA]
    ligands = sorted(p for root in paths for p in ([root] if root.is_file() else sorted(root.glob("*.mol2"))))
    if not ligands:
        parser.error(f"no ligand files found in {[str(p) for p in paths]}")

    args.out.mkdir(parents=True, exist_ok=True)
    matrix = args.out / "matrix.json"
    if args.index_only:
        rows = json.loads(matrix.read_text())
    else:
        print(f"Planning {len(VARIANTS)} variants over {len(ligands)} ligands into {args.out}")
        rows = run_matrix(ligands, args.out, args.jobs)
        matrix.write_text(json.dumps(rows, indent=2))

    path = build_index(rows, args.out, len(ligands))
    failed = [r["key"] for r in rows if "error" in r]
    print(f"\nwrote {path} ({len(rows)} variants)")
    if failed:
        print(f"{len(failed)} variant(s) failed to plan: {', '.join(failed)}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
